/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_t_vector (XDR *xdrs, t_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->t_vector_val, (u_int *) &objp->t_vector_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_potencia (XDR *xdrs, potencia *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->base))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->exponente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_1_argument (XDR *xdrs, multiplicar_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_1_argument (XDR *xdrs, dividir_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_escalar_1_argument (XDR *xdrs, producto_escalar_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escalar_por_vector_1_argument (XDR *xdrs, escalar_por_vector_1_argument *objp)
{
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_vectores_1_argument (XDR *xdrs, suma_vectores_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_vectores_1_argument (XDR *xdrs, resta_vectores_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_vectorial_1_argument (XDR *xdrs, producto_vectorial_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_mixto_1_argument (XDR *xdrs, producto_mixto_1_argument *objp)
{
	 if (!xdr_t_vector (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_t_vector (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_potencias_1_argument (XDR *xdrs, multiplicar_potencias_1_argument *objp)
{
	 if (!xdr_potencia (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_potencia (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_potencias_1_argument (XDR *xdrs, dividir_potencias_1_argument *objp)
{
	 if (!xdr_potencia (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_potencia (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
