/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static float *
_sumar_1 (sumar_1_argument *argp, struct svc_req *rqstp)
{
	return (sumar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static float *
_restar_1 (restar_1_argument *argp, struct svc_req *rqstp)
{
	return (restar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static float *
_multiplicar_1 (multiplicar_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static float *
_dividir_1 (dividir_1_argument *argp, struct svc_req *rqstp)
{
	return (dividir_1_svc(argp->arg1, argp->arg2, rqstp));
}

static float *
_producto_escalar_1 (producto_escalar_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_escalar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static t_vector *
_escalar_por_vector_1 (escalar_por_vector_1_argument *argp, struct svc_req *rqstp)
{
	return (escalar_por_vector_1_svc(argp->arg1, argp->arg2, rqstp));
}

static t_vector *
_suma_vectores_1 (suma_vectores_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_vectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static t_vector *
_resta_vectores_1 (resta_vectores_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_vectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static t_vector *
_producto_vectorial_1 (producto_vectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_vectorial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static float *
_producto_mixto_1 (producto_mixto_1_argument *argp, struct svc_req *rqstp)
{
	return (producto_mixto_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static float *
_media_1 (t_vector  *argp, struct svc_req *rqstp)
{
	return (media_1_svc(*argp, rqstp));
}

static float *
_potencia_1 (potencia  *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(*argp, rqstp));
}

static potencia *
_multiplicar_potencias_1 (multiplicar_potencias_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicar_potencias_1_svc(argp->arg1, argp->arg2, rqstp));
}

static potencia *
_dividir_potencias_1 (dividir_potencias_1_argument *argp, struct svc_req *rqstp)
{
	return (dividir_potencias_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		sumar_1_argument sumar_1_arg;
		restar_1_argument restar_1_arg;
		multiplicar_1_argument multiplicar_1_arg;
		dividir_1_argument dividir_1_arg;
		producto_escalar_1_argument producto_escalar_1_arg;
		escalar_por_vector_1_argument escalar_por_vector_1_arg;
		suma_vectores_1_argument suma_vectores_1_arg;
		resta_vectores_1_argument resta_vectores_1_arg;
		producto_vectorial_1_argument producto_vectorial_1_arg;
		producto_mixto_1_argument producto_mixto_1_arg;
		t_vector media_1_arg;
		potencia potencia_1_arg;
		multiplicar_potencias_1_argument multiplicar_potencias_1_arg;
		dividir_potencias_1_argument dividir_potencias_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMAR:
		_xdr_argument = (xdrproc_t) xdr_sumar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _sumar_1;
		break;

	case RESTAR:
		_xdr_argument = (xdrproc_t) xdr_restar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _restar_1;
		break;

	case MULTIPLICAR:
		_xdr_argument = (xdrproc_t) xdr_multiplicar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _multiplicar_1;
		break;

	case DIVIDIR:
		_xdr_argument = (xdrproc_t) xdr_dividir_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _dividir_1;
		break;

	case PRODUCTO_ESCALAR:
		_xdr_argument = (xdrproc_t) xdr_producto_escalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_1;
		break;

	case ESCALAR_POR_VECTOR:
		_xdr_argument = (xdrproc_t) xdr_escalar_por_vector_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _escalar_por_vector_1;
		break;

	case SUMA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_suma_vectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _suma_vectores_1;
		break;

	case RESTA_VECTORES:
		_xdr_argument = (xdrproc_t) xdr_resta_vectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _resta_vectores_1;
		break;

	case PRODUCTO_VECTORIAL:
		_xdr_argument = (xdrproc_t) xdr_producto_vectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_t_vector;
		local = (char *(*)(char *, struct svc_req *)) _producto_vectorial_1;
		break;

	case PRODUCTO_MIXTO:
		_xdr_argument = (xdrproc_t) xdr_producto_mixto_1_argument;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _producto_mixto_1;
		break;

	case MEDIA:
		_xdr_argument = (xdrproc_t) xdr_t_vector;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _media_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_potencia;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case MULTIPLICAR_POTENCIAS:
		_xdr_argument = (xdrproc_t) xdr_multiplicar_potencias_1_argument;
		_xdr_result = (xdrproc_t) xdr_potencia;
		local = (char *(*)(char *, struct svc_req *)) _multiplicar_potencias_1;
		break;

	case DIVIDIR_POTENCIAS:
		_xdr_argument = (xdrproc_t) xdr_dividir_potencias_1_argument;
		_xdr_result = (xdrproc_t) xdr_potencia;
		local = (char *(*)(char *, struct svc_req *)) _dividir_potencias_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALCULADORAVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORAVERS, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORAVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORAVERS, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORAVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
